name: Terraform Check

on:
  push:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform format
        run: terraform fmt -check -recursive
      - name: Terraform init without backend
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate
